# Hexo Configuration
# Docs: https://hexo.io/docs/configuration.html
# Source: https://github.com/hexojs/hexo/

# Site
title: IDGI
subtitle: 'Follow Back'
description: 'web å­¦ä¹ è€…'
keywords:
author: attractiveboy
language: cn
timezone: 'Asia/Shanghai'

# URL
# Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://attractiveboy.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: music/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
# https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
# Hexo uses Moment.js to parse and display date
# You can customize the date format as defined in
# http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
# Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
# include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
# Plugins: https://hexo.io/plugins/
# Themes: https://hexo.io/themes/
theme: hexo-theme-aomori

# Deployment
# Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:attractive-boy/attractive-boy.github.io.git
  branch: main
# å¤´åƒ
aomori_logo: /ico/Mario.ico

# ç«™ç‚¹æ‰“å­—åŠ¨ç”»
aomori_logo_typed_animated: true

# å¤´éƒ¨èœå•
aomori_menu:
  Home: /
  Archives: /archives
  Music: /music

# ä¾§è¾¹æ èœå•
aomori_widgets:
  - toc # æ–‡ç« å¯¼èˆª
  - category  #æ–‡ç« åˆ†ç±»
  - tag # æ–‡ç« æ ‡ç­¾
  - recent_posts  # æœ€æ–°æ–‡ç« 
  - archive #æ–‡ç« å½’æ¡£

# çŸ¥è¯†å…±äº«ä½¿ç”¨è®¸å¯
aomori_copyright: true # or false

# ç¤¾äº¤åª’ä½“
aomori_social:
  -
    icon: github
    type: logo
    url: https://github.com/attractive-boy
  -
    icon:
    type:
    url:

# ç™¾åº¦é“¾æ¥æäº¤
aomori_baidu_sitepush: true  

# ç™¾åº¦ç»Ÿè®¡
# aomori_baidu_analytics: 'a5b64319b7941e0cb3c0cb4aad7c4cea'

# Google ç»Ÿè®¡
# aomori_google_analytics: 'UA-XXXXX-X'

# Google Site Verification
# aomori_google_site:
# enable: true
# id: XXX

# ä¸è’œå­ ç»Ÿè®¡
# aomori_busuanzi: true

# Emoji Favicon
# aomori_favicon: ğŸ® 

#comment
aomori_valine:
  enable: false
  appId: 'YxzXQwNe3AulCfVPAum45S6T-gzGzoHsz'
  appKey: 'cuKhuVs45xUM7PeKxjeR4M6Y'
  

# aomori_gitalk:
#   enable: true
#   clientID: 97ff5e0e940c54e6f525
#   clientSecret: a8f7deaf784f0c416c47295984a8081ba9cce048
#   repo: IDGI-gitalk
#   owner: attractive-boy
#   admin: 
#     - attractive-boy
#   distractionFreeMode: true // Facebook-like distraction free mode

# Extensions
# Plugins: http://hexo.io/plugins/
# RSSè®¢é˜…
plugin:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

backup:
  type: git
  theme: hexo-theme-aomori
  message: Back up my www.attractiveboy.top blog
  repository:
    github: git@github.com:attractive-boy/attractive-boy.github.io.git,backup
    coding: git@git.dev.tencent.com:attractive-boy/attractive-boy.git,backup

algolia:
  applicationID: '53D19Y7XVE'
  apiKey: '4cf3813afab1cda9a5d89eadf450864b'
  indexName: 'IDGI'

aomori_search_algolia: true

rss: /atom.xml

